2016-10-01 14:57:51,348 manager INFO 1.1.0
2016-10-01 14:57:51,348 manager INFO Copyright (C) 2003-2010
2016-10-01 14:57:51,348 manager INFO   Noriaki Ando
2016-10-01 14:57:51,348 manager INFO   Intelligent Systems Research Institute, AIST
2016-10-01 14:57:51,348 manager INFO Manager starting.
2016-10-01 14:57:51,348 manager INFO Starting local logging.
2016-10-01 14:57:51,357 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2016-10-01 14:57:53,364 ManagerServant INFO Master manager not found
2016-10-01 14:57:53,365 manager WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2016-10-01 14:57:53,365 LocalServiceAdmin INFO All the local services are enabled.
2016-10-01 14:57:53,378 ec_base INFO setRate(1000000.000000) done
2016-10-01 14:57:53,378 ec_base INFO setRate(1000.000000) done
2016-10-01 14:57:53,380 rtobject INFO 1 execution context was created.
2016-10-01 14:57:53,385 rtobject INFO Initial active configuration set is default.
2016-10-01 14:57:55,875 SdoServiceAdmin WARNING No available SDO service in the factory: 
2016-10-01 14:57:55,875 SdoServiceAdmin ERROR type  already exists.
2016-10-01 14:57:55,881 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2016-10-01 14:57:55,881 SdoServiceAdmin ERROR type bc75313b-6be0-4812-84d2-1a23e480c99f already exists.
2016-10-01 14:58:55,673 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 334, in onExecute
    self.Send(0x03,VR*CntPM)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 370, in Send
    self.SPort.write(MakeData(ID,Data))
  File "C:\Python27\Lib\site-packages\serial\serialwin32.py", line 322, in write
    raise writeTimeoutError
SerialTimeoutException: Write timeout

2016-10-01 14:58:55,674 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1359, in on_deactivated
    ret = self.onDeactivated(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 304, in onDeactivated
    self.Send(0x78,False)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 370, in Send
    self.SPort.write(MakeData(ID,Data))
  File "C:\Python27\Lib\site-packages\serial\serialwin32.py", line 322, in write
    raise writeTimeoutError
SerialTimeoutException: Write timeout

2016-10-01 14:59:16,262 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-10-01 14:59:16,269 ec_worker WARNING ExecutionContext is already stopped.
2016-10-01 14:59:16,269 ec_base ERROR Invoking on_shutdown() for each RTC failed.
