2016-10-01 15:01:52,397 manager INFO 1.1.0
2016-10-01 15:01:52,397 manager INFO Copyright (C) 2003-2010
2016-10-01 15:01:52,397 manager INFO   Noriaki Ando
2016-10-01 15:01:52,397 manager INFO   Intelligent Systems Research Institute, AIST
2016-10-01 15:01:52,397 manager INFO Manager starting.
2016-10-01 15:01:52,398 manager INFO Starting local logging.
2016-10-01 15:01:52,415 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2016-10-01 15:01:54,424 ManagerServant INFO Master manager not found
2016-10-01 15:01:54,427 manager WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2016-10-01 15:01:54,427 LocalServiceAdmin INFO All the local services are enabled.
2016-10-01 15:01:54,447 ec_base INFO setRate(1000000.000000) done
2016-10-01 15:01:54,447 ec_base INFO setRate(1000.000000) done
2016-10-01 15:01:54,448 rtobject INFO 1 execution context was created.
2016-10-01 15:01:54,463 rtobject INFO Initial active configuration set is default.
2016-10-01 15:02:23,065 SdoServiceAdmin WARNING No available SDO service in the factory: 
2016-10-01 15:02:23,066 SdoServiceAdmin ERROR type  already exists.
2016-10-01 15:02:23,112 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2016-10-01 15:02:23,112 SdoServiceAdmin ERROR type 88662a03-9979-4867-aaf0-18f089bc24c5 already exists.
2016-10-01 15:04:59,653 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:10:05,444 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-10-01 15:13:41,266 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:14:05,569 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:15:37,829 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:16:06,232 InPortCorbaCdrConsumer ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\InPortCorbaCdrConsumer.py", line 157, in put
    return self.convertReturnCode(inportcdr.put(data))
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTM_IDL\DataPort_idl.py", line 79, in put
    return self._obj.invoke("put", _0_OpenRTM.InPortCdr._d_put, args)
COMM_FAILURE: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_WaitingForReply, CORBA.COMPLETED_MAYBE)

2016-10-01 15:16:07,256 Axis WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\PortBase.py", line 1624, in disconnectNext
    return p.notify_disconnect(connector_profile.connector_id)
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTM_IDL\RTC_idl.py", line 1207, in notify_disconnect
    return self._obj.invoke("notify_disconnect", _0_RTC.PortService._d_notify_disconnect, args)
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

2016-10-01 15:16:08,259 InPortCorbaCdrConsumer ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\InPortCorbaCdrConsumer.py", line 157, in put
    return self.convertReturnCode(inportcdr.put(data))
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTM_IDL\DataPort_idl.py", line 79, in put
    return self._obj.invoke("put", _0_OpenRTM.InPortCdr._d_put, args)
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

