2016-09-23 13:12:21,562 manager INFO 1.1.0
2016-09-23 13:12:21,562 manager INFO Copyright (C) 2003-2010
2016-09-23 13:12:21,562 manager INFO   Noriaki Ando
2016-09-23 13:12:21,562 manager INFO   Intelligent Systems Research Institute, AIST
2016-09-23 13:12:21,562 manager INFO Manager starting.
2016-09-23 13:12:21,562 manager INFO Starting local logging.
2016-09-23 13:12:21,578 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2016-09-23 13:12:23,716 ManagerServant INFO Master manager not found
2016-09-23 13:12:23,716 manager WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2016-09-23 13:12:23,716 LocalServiceAdmin INFO All the local services are enabled.
2016-09-23 13:12:23,716 ec_base INFO setRate(1000000.000000) done
2016-09-23 13:12:23,716 ec_base INFO setRate(1000.000000) done
2016-09-23 13:12:23,716 rtobject INFO 1 execution context was created.
2016-09-23 13:12:23,716 rtobject INFO Initial active configuration set is default.
2016-09-23 13:12:35,888 SdoServiceAdmin WARNING No available SDO service in the factory: 
2016-09-23 13:12:35,888 SdoServiceAdmin ERROR type  already exists.
2016-09-23 13:12:35,890 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2016-09-23 13:12:35,890 SdoServiceAdmin ERROR type 3108ab9b-b229-414f-a5ca-84ec92d094cf already exists.
2016-09-23 13:16:41,493 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1319, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 278, in onActivated
    self.SPort=serial.Serial(self._Port[0],timeout=TimeOut)
  File "C:\Python27\Lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\serial\serialutil.py", line 182, in __init__
    self.open()
  File "C:\Python27\Lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM1': WindowsError(2, '\x8ew\x92\xe8\x82\xb3\x82\xea\x82\xbd\x83t\x83@\x83C\x83\x8b\x82\xaa\x8c\xa9\x82\xc2\x82\xa9\x82\xe8\x82\xdc\x82\xb9\x82\xf1\x81B')

2016-09-23 13:16:41,499 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 333, in onExecute
    self.Send(0x02,VL*CntPM)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 370, in Send
    self.SPort.write(MakeData(ID,Data))
AttributeError: 'NoneType' object has no attribute 'write'

2016-09-23 13:16:41,500 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1359, in on_deactivated
    ret = self.onDeactivated(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 304, in onDeactivated
    self.Send(0x78,False)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 370, in Send
    self.SPort.write(MakeData(ID,Data))
AttributeError: 'NoneType' object has no attribute 'write'

2016-09-23 13:16:43,451 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-09-23 13:16:46,549 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-09-23 13:16:46,555 ec_worker WARNING ExecutionContext is already stopped.
2016-09-23 13:16:46,555 ec_base ERROR Invoking on_shutdown() for each RTC failed.
2016-10-04 11:57:16,240 manager INFO 1.1.0
2016-10-04 11:57:16,259 manager INFO Copyright (C) 2003-2010
2016-10-04 11:57:16,259 manager INFO   Noriaki Ando
2016-10-04 11:57:16,259 manager INFO   Intelligent Systems Research Institute, AIST
2016-10-04 11:57:16,259 manager INFO Manager starting.
2016-10-04 11:57:16,259 manager INFO Starting local logging.
2016-10-04 11:57:16,278 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2016-10-04 11:57:18,282 ManagerServant INFO Master manager not found
2016-10-04 11:57:18,286 manager WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2016-10-04 11:57:18,286 LocalServiceAdmin INFO All the local services are enabled.
2016-10-04 11:57:18,308 ec_base INFO setRate(1000000.000000) done
2016-10-04 11:57:18,308 ec_base INFO setRate(1000.000000) done
2016-10-04 11:57:18,309 rtobject INFO 1 execution context was created.
2016-10-04 11:57:18,322 rtobject INFO Initial active configuration set is default.
2016-10-04 11:57:42,000 SdoServiceAdmin WARNING No available SDO service in the factory: 
2016-10-04 11:57:42,002 SdoServiceAdmin ERROR type  already exists.
2016-10-04 11:57:42,005 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2016-10-04 11:57:42,005 SdoServiceAdmin ERROR type be713ca4-9b46-4473-9ceb-f57d3eb152a4 already exists.
2016-10-04 12:02:01,246 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-04 12:02:22,901 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-04 12:12:15,979 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-10-04 12:49:31,552 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-10-04 12:49:32,732 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
